dalle_output_file_name : final2_fashion_16_12_30ep_5

epochs : 30                   

save_every_n_steps : 100

batch_size : 5

learning_rate : 4.5e-4

model_dimension : 312

text_sequence_length : 512                   

depth : 16                

heads : 12    

head_dimension : 64                

dataset : ./Local_Dalle/images/fashion_items 
